version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app-container
    ports:
      - "3000:3000"
    volumes:
      - .:/app  
    environment:
      - NODE_ENV=production
      
    env_file: 
      - .env
    restart: always
